import os
import sqlite3
import psycopg
from psycopg import sql
from dotenv import load_dotenv

load_dotenv()

SQLITE_DB = "hardware_inventory.db"
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set in environment or .env file.")

sqlite_conn = sqlite3.connect(SQLITE_DB)
sqlite_conn.row_factory = sqlite3.Row
pg_conn = psycopg.connect(DATABASE_URL)
pg_conn.autocommit = False

try:
    pg_cur = pg_conn.cursor()
    sqlite_cur = sqlite_conn.cursor()

    # -------------------------------------------------------------------------
    # Table definitions derived from hardware_inventory.db
    #
    # Tables (6):
    #   users, hardware, reset_requests, account_requests,
    #   borrow_requests, quantity_additions
    #
    # Foreign keys:
    #   borrow_requests.item_id  → hardware.item_id
    #   quantity_additions.item_id → hardware.item_id
    #
    # NOTE: hardware must be created before the two tables that reference it.
    # -------------------------------------------------------------------------

    table_definitions = {
        "users": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT UNIQUE NOT NULL",
            "email TEXT",
            "password_hash TEXT NOT NULL",
            "failed_attempts INTEGER DEFAULT 0",
            "locked_until REAL DEFAULT 0",
            "role TEXT DEFAULT 'User'",
            "locked INTEGER DEFAULT 0",
        ],
        "hardware": [
            "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "item_name TEXT UNIQUE NOT NULL",
            "category TEXT NOT NULL",
            "quantity INTEGER NOT NULL",
            "unit_price DOUBLE PRECISION NOT NULL",
            "status TEXT NOT NULL",
            "initial_quantity INTEGER NOT NULL DEFAULT 0",
        ],
        "reset_requests": [
            "request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT NOT NULL",
            "email TEXT NOT NULL",
            "new_password_hash TEXT NOT NULL",
            "timestamp TEXT NOT NULL",
            "status TEXT NOT NULL DEFAULT 'pending'",
        ],
        "account_requests": [
            "request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT UNIQUE NOT NULL",
            "email TEXT NOT NULL",
            "password_hash TEXT NOT NULL",
            "role TEXT NOT NULL",
            "timestamp TEXT NOT NULL",
            "status TEXT NOT NULL DEFAULT 'pending'",
        ],
        "borrow_requests": [
            "request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT NOT NULL",
            "item_id BIGINT NOT NULL REFERENCES hardware(item_id) ON DELETE CASCADE",
            "quantity INTEGER NOT NULL",
            "timestamp TEXT NOT NULL",
            "status TEXT NOT NULL DEFAULT 'pending'",
            "batch_id TEXT",
        ],
        "quantity_additions": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "item_id BIGINT NOT NULL REFERENCES hardware(item_id) ON DELETE CASCADE",
            "added_quantity INTEGER NOT NULL",
            "timestamp TEXT NOT NULL",
        ],
    }

    # Primary-key columns used for sequence synchronisation after data load
    sequence_columns = {
        "users": "id",
        "hardware": "item_id",
        "reset_requests": "request_id",
        "account_requests": "request_id",
        "borrow_requests": "request_id",
        "quantity_additions": "id",
    }

    # -------------------------------------------------------------------------
    # 1. Create tables
    # -------------------------------------------------------------------------
    for table_name, columns in table_definitions.items():
        column_sql = sql.SQL(", ").join(sql.SQL(col) for col in columns)
        pg_cur.execute(
            sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(
                sql.Identifier(table_name), column_sql
            )
        )

    # -------------------------------------------------------------------------
    # 2. Check destination tables are empty, then migrate rows
    # -------------------------------------------------------------------------
    counts = {}

    for table_name in table_definitions:
        pg_cur.execute(
            sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table_name))
        )
        if pg_cur.fetchone()[0] > 0:
            raise RuntimeError(f"Destination table '{table_name}' is not empty.")

        sqlite_cur.execute(f"SELECT * FROM {table_name}")
        rows = sqlite_cur.fetchall()
        counts[table_name] = len(rows)

        if not rows:
            continue

        source_columns = [desc[0] for desc in sqlite_cur.description]
        col_ids = sql.SQL(", ").join(sql.Identifier(c) for c in source_columns)
        placeholders = sql.SQL(", ").join(sql.Placeholder() for _ in source_columns)
        insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
            sql.Identifier(table_name), col_ids, placeholders
        )

        for row in rows:
            pg_cur.execute(insert_sql, [row[c] for c in source_columns])

    # -------------------------------------------------------------------------
    # 3. Synchronise PostgreSQL identity sequences
    # -------------------------------------------------------------------------
    for table_name, id_col in sequence_columns.items():
        pg_cur.execute(
            sql.SQL(
                "SELECT setval("
                "  pg_get_serial_sequence({}, {}),"
                "  COALESCE(MAX({}), 0),"
                "  MAX({}) IS NOT NULL"
                ") FROM {}"
            ).format(
                sql.Literal(table_name),
                sql.Literal(id_col),
                sql.Identifier(id_col),
                sql.Identifier(id_col),
                sql.Identifier(table_name),
            )
        )

    pg_conn.commit()

    print("Migration completed successfully.")
    print()
    for table_name, count in counts.items():
        print(f"  {table_name:<22}: {count} row(s)")

except Exception:
    pg_conn.rollback()
    raise

finally:
    sqlite_conn.close()
    pg_conn.close()